[package]
name = "sumo"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[scripts]
test = "snforge test"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git",tag="v0.13.3"}
universal_ecip = { path = "./universal_ecip" }
erc20 = { path = "./erc20" }
starknet = "2.8.2"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }
# snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git"}
assert_macros = "2.8.4"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
build-external-contracts = ["universal_ecip::UniversalECIP","erc20::ERC20Contract"]
# casm = true
# casm-add-pythonic-hints = true


