[workspace]
members = [
    "sumo_login",
    "sumo_account"
]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[workspace.dependencies]
starknet = "^2.8.0"


[workspace.package]
# name = "sumo_login_starknet"
version = "0.1.0"
edition = "2024_07"
