[workspace]
members = [
    "sumo_login",
    "sumo_account"
]


[workspace.package]
name = "sumo_login_starknet"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[scripts]
test = "snforge test"

[workspace.dependencies]
starknet = "^2.8.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }
