[package]
name = "sumo_account"
version.workspace = true
edition.workspace = true

[dependencies]
starknet = { workspace = true }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.30.0" }

[[target.starknet-contract]]
sierra = true
casm = false
casm-add-pythonic-hints = false
allowed-libfuncs-list.name = "experimental"
